### ISSUE TITLE
ImportError: cannot import name Connection

### ISSUE THREAD

**Issue by raphaelgon** [oisinmulvihill/nozama-cloudsearch#12]
Hi,

I am giving your code a try. I am using the mongodb image container on docker. 

I installed some packages before following the steps on "Quickstart":

apt-get update
apt-get upgrade

apt-get install python-dev build-essential wget vim
apt-get install python-pip
pip install --upgrade pip

pip install virtualenv

python -m pip install pymongo

Then I followed the instructions on Quickstart:

virtualenv nozama
source nozama/bin/activate
easy_install nozama-cloudsearch-service / pip install nozama-cloudsearch-service

wget https://raw.github.com/oisinmulvihill/nozama-cloudsearch/master/nozama-cloudsearch-service/development.ini

pserve development.ini

The mongodb is up and running.

This is the error message that I received:

File "/nozama/lib/python2.7/site-packages/nozama_cloudsearch_data-1.1.3-py2.7.egg/nozama/cloudsearch/data/db.py", line 6, in <module>
    from pymongo import Connection
ImportError: cannot import name Connection

Thank you for your help,

Raphael

**Comment by mr-sudaca** [comment]
@raphaelgon 

Had the same problem and I found this: https://stackoverflow.com/questions/29690786/python-mogo-importerror-cannot-import-name-connection

you need to downgrade pymongo to version 2.7.2. That worked for me

**Comment by oisinmulvihill** [comment]
Hello,

I haven't had a chance to sit down and bring this project up to date. I'd welcome on pull requests to make it better.

**Comment by oisinmulvihill** [comment]
I'm in the process of updating this project at the moment, which should resolve these issues too.

**Comment by oisinmulvihill** [comment]
I've fixed this now and nozama-cloudsearch is the way forward https://pypi.org/project/nozama-cloudsearch/ you can also use docker to if you want https://hub.docker.com/r/oisinmulvihill/nozama-cloudsearch.
