### ISSUE TITLE
Version  for easy_install is out of date

### ISSUE THREAD

**Issue by owenj62** [oisinmulvihill/nozama-cloudsearch#13]
When using easy_install, the version pulled is 1.1.3 yet the latest version is 1.2.0
Please can this be updated?

It's this particular commit i'm after, i've tried building it from Source using Docker but seem to be running in to various issues. I'm not a Python Developer either 😄
https://github.com/oisinmulvihill/nozama-cloudsearch/commit/168333b3d4ccacdb89f5538390444d2b1b75ff30

**Comment by owenj62** [comment]
It's this particular commit i'm after, i've tried building it from Source using Docker but seem to be running in to various issues. I'm not a Python Developer either 😄 
https://github.com/oisinmulvihill/nozama-cloudsearch/commit/168333b3d4ccacdb89f5538390444d2b1b75ff30

**Comment by oisinmulvihill** [comment]
I'm in the process of updating this project. I haven't worked on it in a long time and only just noticed people have been using it. I'll get back to you in the next few days once I'm finished

**Comment by owenj62** [comment]
Awesome, thanks a lot 👍

**Comment by oisinmulvihill** [comment]
I've fixed this now although I've change to a single package which is now called nozama-cloudsearch. I'd recommend the docker + docker compose approach to get up and running fast. Have a look at the quick start instructions here https://github.com/oisinmulvihill/nozama-cloudsearch#id7.
